[common]
csvfilename = "waiting.csv"
outputfilename = "output.csv"
logfilename = "log.txt"
Columns = "2,3-4,5"
minlength = 2

[LLM]
api = "https://api.openai.com/v1/chat/completions"
apikey = "sk-1234567890abcdef1234567890abcdef"
model = "gpt-4o-mini"
lang = "en"
prompt = "You are a professional, authentic machine translation engine. Translate text to {lang}, preserving structure, codes, and markup."
isParallelProcessing = false
signParallelProcessing = "||"
promptParallelProcessing = "Separate translations with {signParallelProcessing}."

[connection]
isProxy = false
address = ""
port = ""
username = ""
password = ""